name: Windows Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  library_name: botan
  triplet: x64-windows-custom
  
jobs:
  build:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - name: Install ${{ env.library_name }}
        shell: cmd
        run: |
          git clone https://github.com/microsoft/vcpkg
          cd vcpkg
          git checkout 3dd12b903561148b931de27f10f7f603db8e0171 -- ports/${{ env.library_name }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Windows-artifact
          path: ${{github.workspace}}/vcpkg/ports/${{ env.library_name }}
          if-no-files-found: ignore
          include-hidden-files: true
          retention-days: 0
