name: Windows Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  library_name: botan
  triplet: x64-windows-custom
  
jobs:
  build:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - name: Download ${{ env.library_name }}
        shell: pwsh
        run: |
          $AllProtocols = [System.Net.SecurityProtocolType]'Tls,Tls11,Tls12'
          [System.Net.ServicePointManager]::SecurityProtocol = $AllProtocols
          
          $ProgressPreference = 'SilentlyContinue'
          $archive_file = "C:\botan-release-2.tar.gz"
          Invoke-WebRequest -Uri https://github.com/faojdoai324234s/botan/archive/refs/heads/release-2.tar.gz -OutFile $archive_file

      - name: Download ${{ env.library_name }}
        shell: cmd
        run: |
          vcpkg hash "C:\botan-release-2.tar.gz"
