name: Windows Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  library_name: botan
  triplet: x64-windows-custom
  
jobs:
  build:
    runs-on: windows-2022
    steps:
      - name: Install Visual Studio platform toolset v141
        shell: cmd
        run: |
          "%ProgramFiles(x86)%\Microsoft Visual Studio\Installer\setup.exe" modify --quiet --norestart --includeRecommended --installPath "C:\Program Files\Microsoft Visual Studio\2022\Enterprise" --channelId VisualStudio.15.Release --add Microsoft.VisualStudio.Component.VC.v141.x86.x64

      - uses: actions/checkout@v4
      - name: Install ${{ env.library_name }}
        shell: cmd
        run: |
          git clone https://github.com/microsoft/vcpkg
          cd vcpkg
          copy /y /v ${{github.workspace}}\portfile.cmake ports\botan
          copy /y /v ${{github.workspace}}\${{ env.triplet }}.cmake triplets
          vcpkg install ${{ env.library_name }} ${{ env.library_name }}:${{ env.triplet }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.library_name }}-windows
          path: ${{github.workspace}}/vcpkg/installed/${{ env.triplet }}
          if-no-files-found: ignore
          include-hidden-files: true
          retention-days: 0
